import React from "react";
import Timeslot from "./Timeslot";

interface Props {
  timeOfDay: string;
  dates: Date[];
}

const TimeslotGroup: React.FC<Props> = ({ dates, timeOfDay }) => {
  return (
    <div className="flex flex-col">
      <h3 className="capitalize">{timeOfDay}</h3>
      <div className="grid grid-cols-4 gap-4">
        {dates.map((slot: Date, index: number) => (
          // The slot doesn't have an ID so I'll use the index generated by the map as key
          <Timeslot slot={slot} key={index} />
        ))}
      </div>
    </div>
  );
};

export default TimeslotGroup;
