import React from "react";
import Timeslot from "./Timeslot";
import { motion } from "framer-motion";

const list = {
  show: {
    opacity: 1,
    transition: {
      staggerChildren: 0.05,
    },
  },
  hidden: {
    opacity: 1,
  },
};

const item = {
  hidden: { scale: 0 },
  show: { scale: 1 },
};

interface Props {
  timeOfDay: string;
  dates: Date[];
}

const TimeslotGroup: React.FC<Props> = ({ dates, timeOfDay }) => {
  return (
    <div className="flex flex-col">
      <h3 className="capitalize font-light">{timeOfDay}</h3>
      <motion.div
        initial="hidden"
        whileInView="show"
        variants={list}
        className="grid grid-cols-4 gap-2"
      >
        {dates.map((slot: Date, index: number) => (
          // The slot doesn't have an ID so I'll use the index generated by the map as key
          <motion.div variants={item}>
            <Timeslot slot={slot} key={index} />
          </motion.div>
        ))}
      </motion.div>
    </div>
  );
};

export default TimeslotGroup;
